{
 "title": "Ethereum Indexation Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Indexed Block",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "pump_last_processed_block{chain=\"ETHEREUM\"}"
    }
   ]
  },
  {
   "title": "Dowload Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(pump_block_size_bytes_sum{chain=\"ETHEREUM\"}[10s])"
    }
   ]
  },
  {
   "title": "Time To Full Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(pump_last_network_block{chain=\"ETHEREUM\"} - pump_last_processed_block{chain=\"ETHEREUM\"}) / rate(pump_last_processed_block{chain=\"ETHEREUM\"}[10m])"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(pump_block_size_bytes_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(pump_block_size_bytes_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Last Pumped Block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "pump_last_processed_block{chain=\"ETHEREUM\"}",
     "legendFormat": "Indexed Block"
    },
    {
     "expr": "pump_last_network_block{chain=\"ETHEREUM\"}",
     "legendFormat": "Network Block"
    }
   ]
  },
  {
   "title": "Blocks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "locale", "label": "block/sec" }
   ],
   "targets": [
    {
     "expr": "rate(pump_last_processed_block{chain=\"ETHEREUM\"}[10m])"
    }
   ]
  },
  {
   "title": "Block download speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum_over_time(pump_bundle_download_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(pump_bundle_download_seconds_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Single Block Download Time"
    },
    {
     "expr": "1000 * sum_over_time(pump_bundle_kafka_store_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(pump_bundle_kafka_store_seconds_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Kafka Transaction Batch Store Time"
    }
   ]
  }
 ]
}